# The IP protocol number in Ethernet frames.
ETHERNET_IP_PROTO = 0x800

# The UDP protocol number in IP datagrams.
IP_UDP_PROTO = 0x11

# The full size of a BOOTP packet
BOOTP_PACKET_SIZE = 300

# The BOOTP magic cookie value that precedes option fields.
BOOTP_MAGIC_COOKIE = 0x63825363

# BOOTP operation types.
BOOTP_OP_BOOTPREQUEST = 1
BOOTP_OP_BOOTPREPLY = 2

# BOOTP vendor information extensions, as defined in RFC 1497
BOOTP_OPTION_PAD = 0
BOOTP_OPTION_SUBNET = 1
BOOTP_OPTION_OFFSET = 2
BOOTP_OPTION_GATEWAY = 3
BOOTP_OPTION_TIMESERVER = 4
BOOTP_OPTION_IEN_NAMESERVER = 5
BOOTP_OPTION_DNS = 6
BOOTP_OPTION_LOGSERVER = 7
BOOTP_OPTION_QUOTESERVER = 8
BOOTP_OPTION_LPRSERVER = 9
BOOTP_OPTION_IMPRESSSERVER = 10
BOOTP_OPTION_RLPSERVER = 11
BOOTP_OPTION_HOSTNAME = 12
BOOTP_OPTION_BOOTFILESIZE = 13
BOOTP_OPTION_MERITDUMP = 14
BOOTP_OPTION_DOMAINNAME = 15
BOOTP_OPTION_SWAPSERVER = 16
BOOTP_OPTION_ROOTPATH = 17
BOOTP_OPTION_EXTENSION = 18
BOOTP_OPTION_END = 255